name: "Test Examples"

on:
  workflow_dispatch:
  push:
    branches:
      - jw/example-gh-action
  pull_request:

permissions:
  contents: read

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn run build:lib

      # Run the ./scripts/test-examples.mjs file
      - name: Run test-examples.mjs
        run: node ./scripts/test-examples.mjs
